#!/bin/sh
### BEGIN INIT INFO
# Provides:          resize-rootfs
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Expand root filesystem to fill partition on first boot
### END INIT INFO

FLAGFILE=/var/lib/resize-rootfs-done

case "$1" in
    start)
        if [ -f "$FLAGFILE" ]; then
            exit 0
        fi

        ROOT_DEV=$(findmnt -n -o SOURCE /)
        DISK=$(echo "$ROOT_DEV" | sed 's/p[0-9]*$//')
        PART_NUM=$(echo "$ROOT_DEV" | grep -o '[0-9]*$')

        parted -s "$DISK" resizepart "$PART_NUM" 100%
        resize2fs "$ROOT_DEV"

        touch "$FLAGFILE"
        ;;
    stop|restart|reload)
        ;;
esac
